title: "The Lizards Blog (English)"
description: "News and backstage stories from The Lizards world"
baseurl: ""
url: "https://blog-en.thelizards.it"

# Autore
author:
  name: "The Lizards Team"
  email: "info@thelizards.it"

# Build settings
markdown: kramdown
theme: minima
show_excerpts: true
lang: en_US
permalink: /:year/:month/:day/:title/
timezone: Europe/Rome

# Impostazioni di paginazione
paginate: 5
paginate_path: "/page:num/"

sass:
  style: compressed

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Default Open Graph settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image: "/assets/images/The-Lizards-Logo_small.png"
      layout: post
      lang: "en"

# These are files that GitHub Pages should ignore
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github/
  - .gitignore
  - LICENSE
  - node_modules
  - vendor
  - .bundle
  - .git

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
